In [110]:
import numpy as np

В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [111]:
def sigmoid(z):
    return (1 / (1 + np.exp(-z)))

In [112]:
for z in [-2, -1, 0, 1, 2]:
    sigmoid_ = sigmoid(z)
    print(f"sigmoid({z}) =  {round(sigmoid_, 4)}")

sigmoid(-2) =  0.1192
sigmoid(-1) =  0.2689
sigmoid(0) =  0.5
sigmoid(1) =  0.7311
sigmoid(2) =  0.8808




#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [113]:
def hypothesis(theta, X):
    z = np.dot(X, theta)
    return sigmoid(z)

In [114]:
theta = np.array([0.5, -0.5])

X = np.array([
    [1, 2],
    [1, -1],
    [1, 0],
    [1, 1]
])

hypothesis(theta, X)

array([0.37754067, 0.73105858, 0.62245933, 0.5       ])

#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [115]:
def compute_gradient(theta, X, y):
    hyp = hypothesis(theta, X)
    return np.dot(X.T, (hyp - y)) / len(y)

In [116]:
y = np.array([1, 0, 1, 0])

compute_gradient(theta, X, y)

array([ 0.05776464, -0.36899431])


#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [125]:
def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
    theta = np.zeros(X.shape[1])
    for _ in range(epochs):
        gradient = compute_gradient(theta, X, y)
        theta -= lr * gradient
    return theta

In [126]:
full_batch_gradient_descent(X, y, lr=0.1, epochs=100)

array([-0.2893693 ,  0.77655125])

#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [119]:
def predict_proba(theta, X):
    return hypothesis(theta, X)


def predict(theta, X, threshold=0.5):
    return np.where(predict_proba(theta, X) > threshold, 1, 0)


def accuracy(y_true, y_predict):
    return (y_true == y_predict).mean()

In [120]:
new_theta = full_batch_gradient_descent(X, y, lr=0.1, epochs=100)

y_predict_proba = predict_proba(new_theta, X)
print(f"Predicted probabilities of each instance in the matrix X belonging to class 1: {y_predict_proba.round(4)}")

y_predict = predict(new_theta, X)
print(f"Classes of each instance in the matrix X: {y_predict}")

acc = accuracy(y, y_predict)
print(f"Accuracy of the model: {acc}")

Predicted probabilities of each instance in the matrix X belonging to class 1: [0.7797 0.2562 0.4282 0.6194]
Classes of each instance in the matrix X: [1 0 0 1]
Accuracy of the model: 0.5
