### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np
import random

In [12]:
vector = np.random.rand(10)
print(f'Vector: {vector}')
print(f'\nVector shape: {vector.shape}')

Vector: [0.75856854 0.70641189 0.50271737 0.60612006 0.1775732  0.01120358
 0.93117189 0.67456312 0.05532754 0.60619112]

Vector shape: (10,)


In [7]:
vector_uniform = np.array([random.uniform(0, 1) for i in range(10)])
print(f'Vector: {vector_uniform}')
print(f'\nVector shape: {vector_uniform.shape}')

Vector: [0.60312759 0.22035755 0.55934236 0.56534561 0.82356675 0.72592492
 0.07632255 0.096825   0.93868348 0.10433863]

Vector shape: (10,)


In [11]:
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])
print(f'Matrix: {matrix}')
print(f'\nMatrix shape: {matrix.shape}')

Matrix: [[11 14 17]
 [20 23 26]
 [29 32 35]]

Matrix shape: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [15]:
np.round(vector + 10, 2)

array([10.76, 10.71, 10.5 , 10.61, 10.18, 10.01, 10.93, 10.67, 10.06,
       10.61])

In [16]:
matrix * 2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [19]:
vector_square = np.square(vector)
vector_square

array([5.75426230e-01, 4.99017760e-01, 2.52724757e-01, 3.67381532e-01,
       3.15322425e-02, 1.25520182e-04, 8.67081097e-01, 4.55035402e-01,
       3.06113650e-03, 3.67467680e-01])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [20]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [22]:
result_matrix = np.dot(B, A)
display(result_matrix, result_matrix.shape)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

(2, 2)

If `result_matrix` with shape 2x2 is multiplied by a vector `C` with shape 2x1, the resulting matrix will have a shape 2x1

In [24]:
res_1 = np.dot(result_matrix, C)
display(res_1, res_1.shape)

array([[0.5202],
       [0.2846]])

(2, 1)

If `result_matrix` with shape 2x2 is multiplied by another matrix `D` with shape 2x2, the resulting matrix will have a shape 2x2

In [25]:
res_2 = np.dot(result_matrix, D)
display(res_2, res_2.shape)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])

(2, 2)


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [26]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [28]:
vector

array([0.75856854, 0.70641189, 0.50271737, 0.60612006, 0.1775732 ,
       0.01120358, 0.93117189, 0.67456312, 0.05532754, 0.60619112])

In [27]:
vector.T

array([0.75856854, 0.70641189, 0.50271737, 0.60612006, 0.1775732 ,
       0.01120358, 0.93117189, 0.67456312, 0.05532754, 0.60619112])

Transposing a vector does not change its shape. A 1-dimensional vector remains unchanged after transposing

In [31]:
column_vector = np.expand_dims(vector, axis=1)
display(column_vector, column_vector.shape)

array([[0.75856854],
       [0.70641189],
       [0.50271737],
       [0.60612006],
       [0.1775732 ],
       [0.01120358],
       [0.93117189],
       [0.67456312],
       [0.05532754],
       [0.60619112]])

(10, 1)

Using `numpy.expand_dims` with `axis=1` adds an additional dimension to the vector, converting it from a row-vector to a column-vector.

In [33]:
column_vector_transpose = column_vector.T
display(column_vector_transpose, column_vector_transpose.shape)

array([[0.75856854, 0.70641189, 0.50271737, 0.60612006, 0.1775732 ,
        0.01120358, 0.93117189, 0.67456312, 0.05532754, 0.60619112]])

(1, 10)

Transposing a column-vector with 2 dimensions (shape `n x 1`) results in a row-vector also with 2 dimensions (shape `1 x n`).